#!/usr/bin/env bash
if [[ -z $(command -v python) ]]; then
  echo "ERR: Python is required!"
  exit 1
fi

if [[ -z $(command -v pipx) ]]; then
  python -m install pipx -U > /dev/null
fi

if [[ -z $(command -v json-linter) ]]; then
  python -m pipx install json-linter
fi

json-linter ${@}
