on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  tests:
    name: CI Tests
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"
      - run: npm install
      - name: Lint & Sanity Checks
        env: &phalanx
          PHALANX_BASE_URL: https://next.dauntless-builder.com
          PHALANX_API_KEY: static
        run: |
          npm run check # TODO: add biome lint
      - name: Tests
        env: *phalanx
        run: |
          npm run test
      # TODO: readd this
      # - name: Benchmarks
      #   run: |
      #     npm run bench
      #   # only run on pull requests
      #   if: github.event_name == 'pull_request'
